version: "3"
services:


  mysqldb:
    image: mysql:8
    networks:
      - spring-cloud-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb

  app:
    build:
     context: ./
     dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/bootdb
      - SPRING_DATASOURCE_USERNAME=laye
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - mysqldb

networks:
  spring-cloud-network:
    driver: bridge
